### PR TITLE
feat: remove everything except atoms

### LINKED ISSUE #9: Feature: Remove everything except atoms for now
### Type of feature

🍕 Feature

### Current behavior

Screen Shot 2022-11-17 at 9 44 16 AM

### Suggested solution

_No response_

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by shamimbinnur**
## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

#### This PR removes:
- All layouts
- login.tsx
- tools
- context
- interfaces

#### Resets:
- _app.tsx
- index.tsx

#### Uninstalls: 
@headlessui/react
- supabase/gotrue-js
- @supabase/supabase-js
- @supabase/ui": "^0.36.5

#### And:
fixes some minor linting errors (Quotation, Semicolon error)

## Related Tickets & Documents
Fixes #9 

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

### CODE REVIEW

**Comment by shamimbinnur** [comment]
@brandonroberts can you please assist with this error? 

Screenshot 2023-03-18 at 9 10 51 PM

**Comment by bdougie** [comment]
> @brandonroberts @OgDev-01 can you please assist with this error?
> 
> Screenshot 2023-03-18 at 9 10 51 PM

What is the build command and build folder you use locally?

**Comment by bdougie** [comment]
The deploy preview is turned off. 

Screen Shot 2023-03-19 at 10 20 07 PM

**Comment by shamimbinnur** [comment]
> > @brandonroberts @OgDev-01 can you please assist with this error?
> > Screenshot 2023-03-18 at 9 10 51 PM
> 
> What is the build command and build folder you use locally?

@bdougie I tried `npm run build` which produces .next and `npm run build-storybook` which produces storybook-static. None of the build commands gave any error on my local machine.

**Comment by brandonroberts** [comment]
Taking a look into this. It looks like you can set `NEXT_PLUGIN_SKIP=true` as an environment variable to skip any Next configuration. I set that and restarted the build, will see if that helps

**Comment by brandonroberts** [comment]
@shamimbinnur @bdougie the deploy preview is working correctly now

**Comment by shamimbinnur** [comment]
> @shamimbinnur @bdougie the deploy preview is working correctly now

Awesome. Thanks, @brandonroberts!

**Pull request merged**
