### PR TITLE
feat: restructure in order to include multiple design system

### LINKED ISSUE #10: Feature: Add a second Atoms folder for hot.opensauced.pizza components
### Type of feature

🍕 Feature

### Current behavior

This will take time, but we will need each component represented in this design syystem.

### Suggested solution

_No response_

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by shamimbinnur**
## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Descriptiont
In this pull request, I have rearranged certain directories to accommodate several Design Systems within this repository. I have also included a directory for hot.opensauced.pizza along with some test components to demonstrate another design system.

**This PR also renames the `atoms` directory to `primitives`** 

## Related Tickets & Documents
Fixes #10 

## Mobile & Desktop Screenshots/Recordings
From storybook
Screenshot 2023-03-22 at 12 27 52 AM

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

### CODE REVIEW

**Comment by bdougie** [comment]
instead of uppercase, can we use lowercase in the folder structure.?

**Review by bdougie — APPROVED** [review]
Not sure why the build fails on design.opensauced.pizza. Inviting you the sauced-components.netlify.app

update:

It was the build command wasn't set up correctly. I never sent the invite.

**Comment by shamimbinnur** [comment]
> instead of uppercase, can we use lowercase in the folder structure.?

I used uppercase for the parent directory so that it stands out as a separate design system among all the directories. It was just my thinking.

Should I use lowercase instead @bdougie

**Comment by bdougie** [comment]
> > instead of uppercase, can we use lowercase in the folder structure.?
> 
> I used uppercase for the parent directory so that it stands out as a separate design system among all the directories. It was just my thinking.
> 
> Should I use lowercase instead? @bdougie

yes.

**Comment by bdougie** [comment]
This PR organizes the folders, but the components all have no styles. 

Are you able to copy styles from the insights and hot repos in a future PR?

Screen Shot 2023-03-23 at 11 23 28 PM

**Comment by shamimbinnur** [comment]
@bdougie Yes.

**Pull request merged**
